### ISSUE TITLE
Import issue in readUCI

### ISSUE THREAD

**Issue by steveskrip** [LimnoTech/HSPsquared#9]
There's an issue with importing HSP2tools from within the HSP2tools directory. I get the following error when trying to import readUCI on the development branch.

```
In [1]: from readUCI import readUCI
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-f7eac830a7a5> in <module>
----> 1 from readUCI import readUCI

~\Documents\GitHub\HSPsquared\hsp2tools\readUCI.py in <module>
     10
     11 import os.path
---> 12 import HSP2tools
     13
     14

ModuleNotFoundError: No module named 'HSP2tools'
```
I _think_ that you can just refer to modules within the current directory without importing them (I'm a little rusty)?

**Comment by aufdenkampe** [comment]
From May 19 "HSP2 test files from LimnoTech" email  from @steveskrip to @rheaphy, and my response, for our records:

> I’m still having a hard time getting LimnoTech’s HSPF .uci files parsed through the readUCI function. I did get my python path plumbing in order, so thanks for your help with that.
>  
> I think it might be best if I send the files over your way to have a look. I imagine there are just some minor differences in string formatting that aren’t being handled. If you do notice small changes that can be made on the .uci file side, we can do that to get things moving, but I know the goal here is to handle any HSPF .uci file.
>  
> The files are in LimnoTech’s tests branch of the GitHub repository (https://github.com/LimnoTech/HSPsquared/tree/develop/tests). The two tests are GRW_Plaster and ZRW_WestIndian. Let me know if you’d like me to send them over to you another way.

My emailed response:

> I’ve issued a pull request to Bob for all of Steve test files. See https://github.com/respec/HSPsquared/pull/34.
> Bob, once you review and merge this PR, then you’ll be able to work with Steve’s files in your `develop` branch.

Bob merged PR https://github.com/respec/HSPsquared/pull/34 into their develop on May 22. See the PR conversation for some additional details.

From June 2-13, Bob made three commits that refactored `readUCI`. For the list, see https://github.com/respec/HSPsquared/pull/41.

This issue is now connected to the more general https://github.com/respec/HSPsquared/issues/40 "Improve readUCI for a broader range of valid UCI files"

**Comment by aufdenkampe** [comment]
Closing this issue, as the original problem was resolved. 

We'll continue the conversation about general challenges with readUCI in https://github.com/respec/HSPsquared/issues/40.
